build:
  - build/*
  - build-*
chore:
  - chore/*
  - chore-*
ci:
  - ci/*
  - ci-*
feature:
  - feat/*
  - feat-*
fix:
  - fix/*
  - fix-*
performance:
  - perf/*
  - perf-*
refactor:
  - refactor/*
  - refactor-*
test:
  - test/*
  - test-*
docs:
  - docs/*
  - docs-*
